
export class LoginTheme {
  static readonly TITLE: string = '#1A2233'  //拾光印记
  static readonly SLOGAN: string = '#666666' //标语
  static readonly LINK: string = '#4A88FF'  //link
  static readonly PLACEHOLDER: string = '#9CA3AF' //placeholder
  static readonly BUTTON_DARK: string = '#1A2233'  //button_font
  static readonly FOOTER: string = '#94A3B8'  //foot_font
  static readonly SEPARATOR_LINE: string = '#E5E7EB' //divider
  static readonly INPUT_BORDER: string = '#E2E8F0'  //inputborder
  static readonly INPUT_BG: string = '#ffffffff'  //input_bg
}
